// Package assets embeds the compiled static files and HTML templates into the
// binary at build time. The static directory must contain tailwind.min.css and
// htmx.min.js before go build is run (generated by `make static` or the
// Dockerfile Node stage).
package assets

import "embed"

//go:embed templates static
var FS embed.FS
